const assert=require('node:assert/strict');
const test=require('node:test');
const fs=require('node:fs');
const vm=require('node:vm');
const path=require('node:path');
const web=path.resolve(__dirname,'../../main/resources/web');
function moduleUnderTest(){const c={URL,URLSearchParams,setTimeout,clearTimeout,crypto:{randomUUID:()=> 'request-1'}};vm.createContext(c);const p=path.join(web,'production-api.js');if(fs.existsSync(p))vm.runInContext(fs.readFileSync(p,'utf8'),c);assert.ok(c.ProductionAPI,'真实生产 API 模块必须存在');return c.ProductionAPI;}
function fixture(){return {buildId:'build-1',name:'测试团队',phase:'specialists',status:'active',lockVersion:'7',lastEventSeq:'10',currentArtifact:{id:'agent-1',kind:'agent',agentRole:'specialist',currentRevision:{id:'rev-2',revisionNo:2,body:{name:'表达顾问',duty:'组织观点',model:'model-x',tools:['source'],capabilities:['归纳'],boundaries:['信息不足先追问']},systemPrompt:'完整提示词\n必须核对来源。',contentSha256:'hash2',generationStatus:'succeeded',reviewStatus:'pending',sources:[]},revisions:[]},artifacts:[],jobs:[],clarifications:[],messages:[{id:'msg-9',role:'assistant',content:'请审阅',presentation:{artifactId:'agent-1',revisionId:'rev-2',contentSha256:'hash2',scope:'artifact.full'}}]};}
test('完整专家稿绑定服务端展示消息、版本、hash与完整范围',()=>{const A=moduleUnderTest(),s=fixture(),target=A.target(s);assert.equal(A.canReview(s,target),true);const r=A.messageRequest(s,target,'确认完整专家稿','op-1',{type:'approve'});assert.equal(r.content,'确认完整专家稿');assert.equal(r.reviewContext.presentedMessageId,'msg-9');assert.equal(r.reviewContext.contentSha256,'hash2');assert.equal(r.action.scope,'artifact.full');assert.equal(r.expectedLockVersion,'7');});
test('未展示完整提示词、历史版本或未决澄清不可按按钮确认',()=>{const A=moduleUnderTest();for(const change of [s=>s.currentArtifact.currentRevision.systemPrompt='',s=>s.clarifications=[{id:'c',status:'open'}],s=>s.status='paused',s=>s.currentArtifact.dependencyState='stale',s=>s.messages=[]]){const s=fixture();change(s);assert.equal(A.canReview(s,A.target(s)),false);}const s=fixture(),t=A.target(s);t.revision={...t.revision,id:'old'};assert.equal(A.canReview(s,t),false);});
test('自由聊天保留原话、不自行推断审批；无展示上下文仍可提问',()=>{const A=moduleUnderTest(),s=fixture();s.messages=[];const r=A.messageRequest(s,A.target(s),'  修改后就可以\n','op-1');assert.equal(r.content,'  修改后就可以\n');assert.equal(r.action,undefined);assert.equal(r.reviewContext,undefined);});
test('创建沿用选择资料版本，使用PUT和现有CSRF，成功后读服务端',async()=>{const A=moduleUnderTest(),calls=[];const client=A.client(async(p,o)=>{calls.push([p,o]);return {ok:true,status:202,json:async()=>({buildId:'b'})};},()=> 'csrf-fixture');await client.create('b',{teamId:'t',name:'名称',responsibility:'职责',documents:[{documentId:'d',documentVersionId:'v'}]});assert.equal(calls[0][1].method,'PUT');assert.equal(calls[0][1].headers['X-Lab-Token'],'csrf-fixture');assert.equal(calls[0][0],'/api/expert-production/v1/builds/b');assert.equal(JSON.parse(calls[0][1].body).documents[0].documentVersionId,'v');});
test('409与503传递真实错误，不返回模拟成功',async()=>{const A=moduleUnderTest();for(const status of [409,503]){const c=A.client(async()=>({ok:false,status,json:async()=>({error:{code:status===409?'STALE_REVIEW_CONTEXT':'DB_UNAVAILABLE',message:'真实服务错误'}})}),()=> '');await assert.rejects(c.snapshot('b'),e=>e.status===status&&e.message==='真实服务错误');}});
test('来源端点编码chunk和偏移，永不请求任意外链',async()=>{const A=moduleUnderTest(),paths=[];const c=A.client(async(p)=>{paths.push(p);return {ok:true,json:async()=>({})};},()=> '');await c.source('b',{chunkId:'c/1',startOffset:0,endOffset:12});assert.equal(paths[0],'/api/expert-production/v1/builds/b/sources/c%2F1?startOffset=0&endOffset=12');});
test('最终清单使用team.full，摘要使用summary.full',()=>{const A=moduleUnderTest();assert.equal(A.scopeFor({kind:'team_manifest'}),'team.full');assert.equal(A.scopeFor({kind:'book_summary'}),'summary.full');});
test('历史焦点不更改服务端待办；刷新仅按URL身份恢复',()=>{const A=moduleUnderTest(),s=fixture();s.currentArtifact.revisions=[{id:'old',revisionNo:1,body:{},generationStatus:'succeeded'}];s.artifacts=[s.currentArtifact];const t=A.target(s,'agent-1','old');assert.equal(t.revision.id,'old');assert.equal(s.currentArtifact.currentRevision.id,'rev-2');const r=A.route('#production/build-1?artifact=agent-1&revision=old');assert.equal(r.buildId,'build-1');assert.equal(r.revisionId,'old');});
function component(snapshot=fixture(),override={}){const dom=require('./dom-harness.cjs').document(),root=dom.createElement('section');dom.body.append(root);let snap=snapshot;const calls=[];const c={URL,URLSearchParams,document:dom,location:{origin:'http://127.0.0.1:1234'},crypto:{randomUUID:()=> 'ui-op-'+calls.length},setTimeout:()=>0,clearTimeout};vm.createContext(c);for(const file of ['production-api.js','production.js']){const p=path.join(web,file);if(fs.existsSync(p))vm.runInContext(fs.readFileSync(p,'utf8'),c);}assert.ok(c.ProductionUI,'真实管理员生产页面必须存在');const client={list:async()=>({builds:[{buildId:'build-1',name:'测试团队',phase:'specialists',status:'active'}]}),snapshot:async()=>JSON.parse(JSON.stringify(snap)),events:async()=>({events:[]}),message:async(id,p)=>{calls.push(p);return {processingStatus:'queued'};},...override};const ui=c.ProductionUI.create({root,client,onRoute:()=>{},onNew:()=>{}});return {ui,dom,root,calls,setSnapshot:s=>snap=s};}
test('真实响应完整提示词和模型工具可见，重开页面从服务端恢复',async()=>{const b=component();await b.ui.enter({buildId:'build-1'});assert.match(b.root.textContent,/完整提示词\n必须核对来源/);assert.match(b.root.textContent,/model-x/);assert.match(b.root.textContent,/source/);const next=fixture();next.status='paused';b.setSnapshot(next);await b.ui.enter({buildId:'build-1'});assert.match(b.root.textContent,/已暂停/);});
test('409保留管理员输入并刷新状态，没有乐观批准',async()=>{const b=component(fixture(),{message:async()=>{const e=new Error('当前版本已更新');e.status=409;throw e;}});await b.ui.enter({buildId:'build-1'});b.dom.getElementById('ep-input').value='不通过，因为遗漏边界';await b.dom.getElementById('ep-chat-form').fire('submit');assert.equal(b.dom.getElementById('ep-input').value,'不通过，因为遗漏边界');assert.match(b.root.textContent,/当前版本已更新/);assert.match(b.root.textContent,/待确认/);});
test('后台失败和未配置数据库显示真错误，不出现模拟概要',async()=>{const b=component(fixture(),{snapshot:async()=>{const e=new Error('数据库尚未配置');e.status=503;throw e;}});await b.ui.enter({buildId:'build-1'});assert.match(b.root.textContent,/数据库尚未配置/);assert.doesNotMatch(b.root.textContent,/金字塔原理/);});
test('确认点击只发送真实版本化审核请求，不自行进入下一阶段',async()=>{const b=component();await b.ui.enter({buildId:'build-1'});await b.dom.getElementById('ep-approve').fire('click');assert.equal(b.calls.length,1);assert.equal(b.calls[0].action.type,'approve');assert.equal(b.calls[0].action.scope,'artifact.full');assert.equal(b.calls[0].reviewContext.revisionId,'rev-2');assert.match(b.root.textContent,/专业子专家/);});
test('任务控制保留尚未发送的管理员草稿',async()=>{const b=component();await b.ui.enter({buildId:'build-1'});b.dom.getElementById('ep-input').value='请补充边界，暂时不要确认';await b.dom.getElementById('ep-pause').fire('click');assert.equal(b.calls[0].action.type,'pause');assert.equal(b.calls[0].reviewContext,undefined);assert.equal(b.dom.getElementById('ep-input').value,'请补充边界，暂时不要确认');});
test('明确否决按钮发送版本化reject，无原因由服务端追问',async()=>{const b=component();await b.ui.enter({buildId:'build-1'});await b.dom.getElementById('ep-reject').fire('click');assert.equal(b.calls.length,1);assert.equal(b.calls[0].action.type,'reject');assert.equal(b.calls[0].reviewContext.revisionId,'rev-2');});
test('网络结果未知时手动重试复用完整原请求',async()=>{const calls=[];const b=component(fixture(),{message:async(id,p)=>{calls.push(p);if(calls.length===1)throw new TypeError('连接中断');return {processingStatus:'queued'};}});await b.ui.enter({buildId:'build-1'});b.dom.getElementById('ep-input').value='解释来源';await b.dom.getElementById('ep-chat-form').fire('submit');assert.equal(b.dom.getElementById('ep-resend').hidden,false);await b.dom.getElementById('ep-resend').fire('click');assert.equal(calls.length,2);assert.equal(JSON.stringify(calls[0]),JSON.stringify(calls[1]));});
test('历史稿自由提问不附带过期审核身份，原话保持不变',()=>{const A=moduleUnderTest(),s=fixture();s.currentArtifact.revisions=[{...s.currentArtifact.currentRevision,id:'old',contentSha256:'old-hash'}];s.messages.push({id:'old-message',role:'assistant',presentation:{artifactId:'agent-1',revisionId:'old',contentSha256:'old-hash',scope:'artifact.full'}});const target=A.target(s,'agent-1','old');const r=A.messageRequest(s,target,'旧版有哪些不同？','old-question');assert.equal(r.reviewContext,undefined);assert.equal(r.content,'旧版有哪些不同？');});
test('切换到读取失败的新构建不会残留上一构建完成提示',async()=>{let reads=0;const done=fixture();done.status='completed';done.phase='final_review';const b=component(done,{snapshot:async()=>{if(reads++===0)return done;throw new Error('新构建暂不可读');}});await b.ui.enter({buildId:'build-1'});assert.equal(b.dom.getElementById('ep-completion').hidden,false);await b.ui.enter({buildId:'build-2'});assert.equal(b.dom.getElementById('ep-completion').hidden,true);});
test('关键词、问答和最终完整流程均来自真实响应并对应正确scope',async()=>{for(const [kind,body,scope] of [['keyword_rule',{rules:[{specialistKey:'writer',keywords:['汇报','结构']}]},'artifact.full'],['qa_example',{examples:[{question:'如何表达？',answer:'先确认问题，再组织依据。',sourceIds:['s1']}],comparison:'>',threshold:0.9},'artifact.full'],['team_manifest',{summary:'团队完成流程',flow:['关键词匹配','多专家交给主专家路由'],members:[{revisionId:'rev-x'}]},'team.full']]){const s=fixture();s.currentArtifact.kind=kind;s.currentArtifact.currentRevision.body=body;s.messages[0].presentation.scope=scope;const b=component(s);await b.ui.enter({buildId:'build-1'});assert.match(b.root.textContent,new RegExp(kind==='keyword_rule'?'汇报':kind==='qa_example'?'如何表达':'多专家交给主专家路由'));await b.dom.getElementById('ep-approve').fire('click');assert.equal(b.calls[0].action.scope,scope);}});
