const assert=require('node:assert/strict');
const test=require('node:test');
const fs=require('node:fs');
const vm=require('node:vm');
const path=require('node:path');
const {document}=require('./dom-harness.cjs');
const web=path.resolve(__dirname,'../../main/resources/web');
function setup({saved=null,snapshots=[],proposeOverride}={}){
 const dom=document(),root=dom.createElement('section');dom.body.append(root);
 const timers=new Map();let seq=0;const storage=new Map(saved?[['expertWorkbenchSelectionV1',saved]]:[]),posts=[],reviews=[],controls=[],reads=[];
 const c={document:dom,URL,URLSearchParams,location:{origin:'http://localhost'},crypto:{randomUUID:()=>`request-${++seq}`},localStorage:{getItem:k=>storage.get(k)||null,setItem:(k,v)=>storage.set(k,v)},setTimeout:(fn,ms)=>{const id=++seq;timers.set(id,{fn,ms});return id;},clearTimeout:id=>timers.delete(id)};
 vm.createContext(c);for(const file of ['production-api.js','workbench.js']){const p=path.join(web,file);if(fs.existsSync(p))vm.runInContext(fs.readFileSync(p,'utf8'),c);}
 assert.ok(c.WorkbenchUI,'工作台组件必须存在');
 const client={propose:async documents=>{posts.push(JSON.parse(JSON.stringify(documents)));return proposeOverride?proposeOverride(documents):{buildId:'build-1'};},snapshot:async id=>{reads.push(id);return snapshots.length?snapshots.shift():pending();},source:async()=>({text:'<script>不执行</script> 原文',documentVersionId:'v1',pageNo:12,originalPageUrl:'/api/expert-production/v1/builds/build-1/source-versions/v1/pages/12#page=12'}),message:async(id,body)=>{controls.push(body);return {};}};
 const ui=c.WorkbenchUI.create({root,client,onReview:id=>reviews.push(id)});
 const docs=[{id:'d1',title:'书一',versions:[{id:'v1',number:1},{id:'v2',number:2}]},{id:'d2',title:'书二',versions:[{id:'w1',number:1}]}];
 const tick=async ms=>{for(const [id,t] of [...timers])if(t.ms===ms){timers.delete(id);await t.fn();}await Promise.resolve();};
 return {ui,dom,root,docs,posts,reviews,controls,reads,tick,storage};
}
function pending(){return {buildId:'build-1',status:'active',phase:'prelearning',lockVersion:'4',jobs:[{id:'job-1',kind:'prelearn',status:'running',checkpoint:{lastCompletedBatch:1}}],artifacts:[{kind:'learning_unit',currentRevision:{generationStatus:'succeeded'}}],summary:{generationStatus:'queued'},proposal:{sources:[]}};}
function ready(){return {...pending(),phase:'summary',jobs:[],summary:{generationStatus:'succeeded',reviewStatus:'pending',body:{specialists:[{key:'s1',name:'结构顾问',responsibility:'整理观点',methodTitles:['归纳法'],typicalQuestions:['怎样组织报告？'],sourceIds:['chunk-1']}]}} ,proposal:{sources:[{chunkId:'chunk-1',documentVersionId:'v1',pageNo:12,title:'书一'}]}};}
test('API propose posts only selected document identities',async()=>{const c={URL,URLSearchParams};vm.createContext(c);vm.runInContext(fs.readFileSync(path.join(web,'production-api.js'),'utf8'),c);const calls=[];const client=c.ProductionAPI.client(async(p,o)=>{calls.push([p,o]);return {ok:true,json:async()=>({buildId:'b'})};},()=> 'csrf');await client.propose([{documentId:'d1',documentVersionId:'v2'}]);assert.equal(calls[0][0],'/api/expert-production/v1/proposals');assert.equal(calls[0][1].method,'POST');assert.equal(calls[0][1].headers['X-Lab-Token'],'csrf');assert.deepEqual(JSON.parse(calls[0][1].body),{documents:[{documentId:'d1',documentVersionId:'v2'}]});});
test('empty selection never posts; rapid checks collapse and reorder does not duplicate',async()=>{const b=setup();b.ui.setDocuments(b.docs);b.ui.enter();await b.tick(1200);assert.equal(b.posts.length,0);await b.dom.getElementById('wb-check-d1').fire('change');await b.dom.getElementById('wb-check-d2').fire('change');await b.tick(1200);assert.equal(b.posts.length,1);assert.deepEqual(b.posts[0],[{documentId:'d1',documentVersionId:'v2'},{documentId:'d2',documentVersionId:'w1'}]);b.ui.setDocuments([...b.docs].reverse());await b.tick(1200);assert.equal(b.posts.length,1);});
test('selected version change posts exact new identity and stale stored version is discarded',async()=>{const b=setup({saved:JSON.stringify([{documentId:'d1',documentVersionId:'deleted'}])});b.ui.setDocuments(b.docs);b.ui.enter();await b.tick(1200);assert.equal(b.posts.length,0);await b.dom.getElementById('wb-check-d1').fire('change');b.dom.getElementById('wb-version-d1').value='v1';await b.dom.getElementById('wb-version-d1').fire('change');await b.tick(1200);assert.equal(b.posts[0][0].documentVersionId,'v1');});
test('refresh restores selection and retrieves same server build',async()=>{const saved=JSON.stringify([{documentId:'d1',documentVersionId:'v1'}]);const b=setup({saved,snapshots:[ready()]});b.ui.setDocuments(b.docs);b.ui.enter();await b.tick(1200);assert.deepEqual(b.posts[0],[{documentId:'d1',documentVersionId:'v1'}]);assert.deepEqual(b.reads,['build-1']);assert.match(b.root.textContent,/结构顾问/);});
test('pending progress is honest, then candidate sources and review use same build',async()=>{const b=setup({snapshots:[pending(),ready()]});b.ui.setDocuments(b.docs);b.ui.enter();await b.dom.getElementById('wb-check-d1').fire('change');await b.tick(1200);assert.match(b.root.textContent,/预学习/);assert.doesNotMatch(b.root.textContent,/结构顾问/);await b.tick(2000);assert.match(b.root.textContent,/结构顾问/);assert.match(b.root.textContent,/怎样组织报告/);await b.dom.getElementById('wb-source-chunk-1').fire('click');assert.match(b.root.textContent,/<script>不执行<\/script> 原文/);await b.dom.getElementById('wb-review').fire('click');assert.deepEqual(b.reviews,['build-1']);assert.equal(b.posts.length,1);assert.equal(b.controls.length,0);});
test('paused action sends revision-safe control and keeps request id for retry after uncertain response',async()=>{const b=setup({snapshots:[{...pending(),status:'paused',jobs:[]}]});b.ui.setDocuments(b.docs);b.ui.enter();await b.dom.getElementById('wb-check-d1').fire('change');await b.tick(1200);await b.dom.getElementById('wb-resume').fire('click');assert.equal(b.controls[0].action.type,'resume');assert.equal(b.controls[0].expectedLockVersion,'4');assert.ok(b.controls[0].clientRequestId);});
test('old proposal response cannot overwrite newer or empty selection',async()=>{let resolve;const wait=new Promise(r=>resolve=r);const b=setup();b.ui.setDocuments(b.docs);b.ui.enter();const original=b.dom.getElementById('wb-check-d1');await original.fire('change');const stale=b.tick(1200);await Promise.resolve();await original.fire('change');resolve({buildId:'old'});await stale;assert.equal(b.reads.length,0);assert.doesNotMatch(b.root.textContent,/结构顾问/);});
test('historic failed job does not obscure running retry; latest failure offers retry',async()=>{const old={...pending(),jobs:[{id:'old',kind:'prelearn',status:'failed',error:'旧错误'},{id:'new',kind:'prelearn',status:'running'}]};const failed={...pending(),jobs:[{id:'old',kind:'prelearn',status:'failed'},{id:'new',kind:'prelearn',status:'failed',error:'本次失败'}]};const b=setup({snapshots:[old,failed]});b.ui.setDocuments(b.docs);b.ui.enter();await b.dom.getElementById('wb-check-d1').fire('change');await b.tick(1200);assert.equal(b.dom.getElementById('wb-retry'),null);await b.tick(2000);assert.ok(b.dom.getElementById('wb-retry'));assert.match(b.root.textContent,/本次失败/);});
test('late A response never replaces selected B candidate',async()=>{let finishA;const b=setup({proposeOverride:documents=>documents[0].documentVersionId==='v2'?new Promise(r=>finishA=r):Promise.resolve({buildId:'build-B'}),snapshots:[ready()]});b.ui.setDocuments(b.docs);b.ui.enter();await b.dom.getElementById('wb-check-d1').fire('change');const a=b.tick(1200);await Promise.resolve();b.dom.getElementById('wb-version-d1').value='v1';await b.dom.getElementById('wb-version-d1').fire('change');await b.tick(1200);finishA({buildId:'build-A'});await a;assert.deepEqual(b.reads,['build-B']);assert.match(b.root.textContent,/结构顾问/);});
test('failed proposal clears prior candidate and exposes retry',async()=>{let fail=false;const b=setup({proposeOverride:()=>fail?Promise.reject(new Error('生产服务暂不可用')):Promise.resolve({buildId:'build-1'}),snapshots:[ready()]});b.ui.setDocuments(b.docs);b.ui.enter();await b.dom.getElementById('wb-check-d1').fire('change');await b.tick(1200);assert.match(b.root.textContent,/结构顾问/);fail=true;b.dom.getElementById('wb-version-d1').value='v1';await b.dom.getElementById('wb-version-d1').fire('change');await b.tick(1200);assert.doesNotMatch(b.root.textContent,/结构顾问/);assert.match(b.root.textContent,/生产服务暂不可用/);assert.ok(b.dom.getElementById('wb-refresh'));});
