import {jobActive, jobForPage, jobIdentity} from './ranch-job.js';
export const esc = value => String(value ?? '').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const e=esc;
const button=(action,label,attrs='')=>`<button data-action="${action}" ${attrs}>${label}</button>`;
const date=v=>v ? new Date(v).toLocaleDateString('zh-CN') : '';
export function creature(p={},large=false) {
 const color={sage:'#d4dfb9',lilac:'#dcd0ed',peach:'#f1c7b1',sky:'#c2dbe2'}[p.color]||'#d4dfb9';
 const egg=p.stage!=='hatched';
 return `<svg class="creature ${large?'large':''}" viewBox="0 0 180 170" aria-hidden="true"><ellipse cx="90" cy="151" rx="49" ry="9" fill="#647a5320"/>${egg?`<path d="M90 29C68 29 47 73 47 105c0 28 20 45 43 45s43-17 43-45c0-32-21-76-43-76Z" fill="${color}"/><path d="M58 108l18-12 19 12 19-13 13 8" fill="none" stroke="#fff9" stroke-width="5"/><ellipse cx="73" cy="64" rx="7" ry="12" fill="#fff7" transform="rotate(28 73 64)"/><circle cx="82" cy="80" r="3" fill="#536052"/><circle cx="103" cy="80" r="3" fill="#536052"/><path d="M86 89q7 5 12-1" fill="none" stroke="#536052" stroke-width="2" stroke-linecap="round"/>`:`${p.creature==='rabbit'?`<ellipse cx="68" cy="45" rx="14" ry="34" transform="rotate(-10 68 45)" fill="${color}"/><ellipse cx="112" cy="45" rx="14" ry="34" transform="rotate(10 112 45)" fill="${color}"/><ellipse cx="68" cy="44" rx="6" ry="21" fill="#fff7"/><ellipse cx="112" cy="44" rx="6" ry="21" fill="#fff7"/>`:p.creature==='bear'?`<circle cx="53" cy="64" r="18" fill="${color}"/><circle cx="127" cy="64" r="18" fill="${color}"/>`:`<path d="M44 84l1-48 37 27M98 62l36-26 3 49" fill="${color}"/>`}<ellipse cx="90" cy="123" rx="35" ry="29" fill="${color}"/><rect x="45" y="57" width="90" height="73" rx="36" fill="${color}"/><ellipse cx="90" cy="107" rx="27" ry="17" fill="#fff8"/><circle cx="72" cy="88" r="3.5" fill="#47564a"/><circle cx="108" cy="88" r="3.5" fill="#47564a"/><path d="M86 103q4-5 8 0l-4 4Z" fill="#756252"/><path d="M81 111q9 7 18 0" fill="none" stroke="#756252" stroke-width="2" stroke-linecap="round"/><ellipse cx="61" cy="101" rx="7" ry="4" fill="#eeb8a766"/><ellipse cx="119" cy="101" rx="7" ry="4" fill="#eeb8a766"/>`}<path d="M35 150q-5-10-10-8m10 8q0-15 6-19M145 151q3-12 10-15" stroke="#9ead78" fill="none" stroke-width="3" stroke-linecap="round"/></svg>`;
}
export function sourceOptions(items=[]) {return '<option value="">选择私聊或群聊</option>'+items.map(s=>`<option value="${e(s.id)}">${e(s.title)} · ${e(s.scope||'已保存记录')}</option>`).join('');}
function evidence(ids=[],p={},self={}) {
 return ids.map(id=>{let label,text;if(id==='person-notes'){label='我的备注 · 用户转述';text=p.notes;}else if(id==='self-description'){label='我的自述';text=[self.about||p.about,self.style||p.style,self.boundaries||p.boundaries].filter(Boolean).join('\n');}else {const m=[...(p.materials||[]),...(self.materials||[])].find(m=>m.id===id);label=m?`${{them:'对方发言',me:'我的发言',context:'上下文'}[m.speaker]||'材料'} · ${m.label||'原始材料'}`:'来源已不可用';text=m?.text;}return `<details class="evidence"><summary>${e(label)}</summary><p class="preserve">${e(text||'这条来源已被移除，请重新生成。')}</p></details>`;}).join('');
}
function profileEvidence(ids,profile,p,self) {
 const books=new Set((profile.knowledge||[]).map(k=>k.id));
 const allowed=(p.id==='self'?[...(p.materials||[]),...(self.materials||[])]:p.materials||[]).filter(m=>m.speaker===(p.id==='self'?'me':'them'));
 const source={...p,materials:allowed};
 return evidence((ids||[]).map(id=>books.has(id)||String(id).startsWith('K-')||id==='self-description'&&p.id!=='self'||id==='person-notes'&&p.id==='self'?'unavailable-reference':id),source,{});
}
function bookReference(k) {
 return `<details class="evidence book-evidence"><summary>${e(k.title)} · ${e(k.location)}</summary><p class="preserve">${e(k.text)}</p></details>`;
}
export function renderProfile(profile,p={},self={}) {
 if(!profile)return `<div class="blank"><span class="blank-symbol">✧</span><h3>让了解，从真实的话开始</h3><p>补充发言与背景，再生成第一份画像。<br>牧场里的蛋，会在画像生成后孵化。</p></div>`;
 const books=profile.knowledge||[];
 const knowledgeNotice={empty_library:'没有可用书籍，本次画像仅依据已读取材料，未使用书籍方法。',no_match:'未找到相关书籍方法，本次画像仅依据已读取材料。'}[profile.knowledgeStatus];
 return `<div class="profile-summary"><span class="pill ${profile.stale?'amber':''}">${profile.stale?'待更新 · 材料已变化':'有来源的初步画像'}</span><p>${e(profile.summary)}</p><small>材料覆盖 ${e(profile.coverage?.used??0)} / ${e(profile.coverage?.total??p.materials?.length??0)} · ${e(date(profile.createdAt))}</small>${knowledgeNotice?`<p class="hint">${e(knowledgeNotice)}</p>`:''}</div>
 <div class="facet-grid">${(profile.facets||[]).map(f=>`<article class="facet"><div class="between"><h3>${e(f.category)}</h3><span class="tiny">${f.kind==='explicit'?'直接信息':'推测'}</span></div><p>${e(f.text)}</p>
 ${f.scope?`<p class="muted">适用范围：${e(f.scope)}</p>`:''}${f.confidenceReason?`<p class="muted">判断依据：${e(f.confidenceReason)}</p>`:''}
 ${f.evidenceIds?.length?`<h4 class="source-heading">聊天与自述依据</h4>${profileEvidence(f.evidenceIds,profile,p,self)}`:''}
 ${f.counterEvidenceIds?.length?`<h4 class="source-heading">反证与不同情况</h4>${profileEvidence(f.counterEvidenceIds,profile,p,self)}`:''}
 ${f.knowledgeIds?.length?`<h4 class="source-heading">书籍方法参考</h4>${f.knowledgeIds.map(id=>{const k=books.find(k=>k.id===id);return k?bookReference(k):'<p class="muted">书籍方法来源已不可用，请重新生成。</p>';}).join('')}`:''}</article>`).join('')}</div>
 ${books.length?`<section class="profile-knowledge"><h3 class="source-heading">书籍方法参考</h3><p class="muted">书籍提供理解方法，不是这个人的事实证据。</p>${books.map(bookReference).join('')}</section>`:''}
 ${profile.uncertainties?.length?`<section class="uncertainties"><h3>还需要慢慢了解</h3>${profile.uncertainties.map(t=>`<p>○ ${e(t)}</p>`).join('')}</section>`:''}`;
}
const phaseLabels={preparing:'准备材料',knowledge:'检索书籍方法',evidence:'补查聊天依据',reasoning:'整理画像与推断',validating:'核对结构与引用',saving:'保存结果',finished:'执行结束'};
function renderJob(data,ui) {
 const job=jobForPage(data.job,ui);
 if(!job||(['error','interrupted'].includes(job.status)&&ui.dismissedJobId===jobIdentity(job))||!['running','cancelling','error','interrupted','cancelled'].includes(job.status))return '';
 const active=jobActive(job),cancelling=job.status==='cancelling';
 const targetProfile=job.targetId==='self'?data.self:data.people.find(p=>p.id===job.targetId);
 const target=job.targetId==='self'?'我的画像':targetProfile?.name;
 const strategy=job.kind==='strategy';
 const phaseLabel=phase=>strategy&&phase==='reasoning'?'整理相处攻略':phaseLabels[phase];
 const savedResult=strategy?targetProfile?.strategies?.at(-1):targetProfile?.profile;
 const label=cancelling?'正在停止任务，请等待确认':job.status==='interrupted'?'任务已中断，请核对当前结果后再决定是否重新生成。':job.status==='cancelled'?`任务已停止。${savedResult?`已保存的${strategy?'相处攻略':'画像'}仍可查看。`:''}`:job.status==='error'?job.error||'生成失败，请稍后重试':phaseLabel(job.phase)||`正在${strategy?'整理相处攻略':'从材料中生成画像'}`;
 const step=Number.isInteger(job.step)&&Number.isInteger(job.maxSteps)&&job.maxSteps>0?` · 模型步骤 ${e(job.step)} / ${e(job.maxSteps)}`:'';
 const events=(job.events||[]).filter(v=>v.type==='phase').slice(-8);
 return `<div class="${job.status==='error'?'error-banner':'job-banner'}" role="${job.status==='error'?'alert':'status'}">${active?'<span class="spinner"></span>':''}<div class="job-copy">${target?`<small>${e(target)} · ${job.kind==='strategy'?'相处攻略':'画像任务'}</small>`:''}<p>${e(label)}${active?step:''}</p>${active&&job.message?`<p>${e(job.message)}</p>`:''}${active&&events.length?`<details class="job-events"><summary>已收到的执行进度</summary>${events.map(v=>`<p>${e(v.message||phaseLabel(v.phase)||'执行中')}</p>`).join('')}</details>`:''}</div>${cancelling||job.status==='cancelled'?'':button(active?'cancel':'dismiss-job',active?'停止任务':'关闭提示',`class="text-button" ${ui.stopping?'disabled':''} ${job.status==='error'?'aria-label="关闭错误提示"':''} ${job.id?`data-run-id="${e(job.id)}"`:''}`)}</div>`;
}
export function renderStrategy(s,p,self={}) {
 if(!s)return '<div class="blank"><span class="blank-symbol">↗</span><h3>把了解，变成自然的下一步</h3><p>画像准备好后，结合你的目标与当下情境，<br>生成有依据、尊重彼此边界的相处建议。</p></div>';
 return `<article class="strategy-result">${s.stale?'<p class="pill amber">待更新 · 画像或参考资料已变化</p>':''}<p class="lead">${e(s.overview)}</p>${s.situation?`<p class="muted">当时情境：${e(s.situation)}</p>`:''}<div class="steps">${(s.steps||[]).map((v,i)=>`<section><span>${i+1}</span><div><h3>${e(v.title)}</h3><p>${e(v.detail)}</p></div></section>`).join('')}</div>${s.reply?`<div class="reply"><div class="between"><h3>可以这样说</h3>${button('copy','复制参考回应',`class="text-button" data-reply="${e(s.reply)}"`)}</div><p class="preserve">${e(s.reply)}</p><small>按你的语气调整后自行发送</small></div>`:''}${s.why?`<p class="muted">${e(s.why)}</p>`:''}<h3 class="source-heading">行为依据</h3>${evidence(s.evidenceIds,p,self)||'<p class="muted">未附行为引用</p>'}<h3 class="source-heading">知识参考</h3>${(s.knowledge||[]).map(k=>`<details class="evidence book-evidence"><summary>${e(k.title)} · ${e(k.location)}</summary><p class="preserve">${e(k.text)}</p></details>`).join('')||'<p class="muted">本次未引用书架资料</p>'}</article>`;
}
function materials(p) {return `<div class="section-heading"><div><h2>每一份了解，都有来处</h2><p>私聊、群发言或手动补充，明确是谁说的话。</p></div><div class="actions">${button('link-source','关联聊天', 'class="secondary"')}${button('material-add','＋ 粘贴材料','class="primary"')}</div></div><div class="material-list">${(p.materials||[]).map(m=>`<article class="material"><div class="between"><span class="pill">${{them:'对方发言',me:'我的发言',context:'上下文 / 背景'}[m.speaker]||'材料'}</span>${button('material-remove','移除',`class="text-button danger" data-id="${e(m.id)}"`)}</div><p class="preserve">${e(m.text)}</p><small>${e(m.label||'手动材料')} ${m.sourceKey?' · 来自关联记录':''}</small></article>`).join('')||'<div class="blank"><h3>这里还没有材料</h3><p>可以先加一两段真实发言，之后随时补充。</p></div>'}</div>`;}
function home(data) {const hatched=data.people.filter(p=>p.stage==='hatched').length;return `<header class="page-heading"><div><div class="eyebrow">A LITTLE CLOSER, EVERY DAY</div><h1>把在意的人，<br>放进这片小牧场。</h1><p>收集真实的片段，让了解慢慢生长。</p></div>${button('new','＋ 添加一个人','class="primary"')}</header><section class="landscape" aria-label="人物牧场"><div class="sun"></div><div class="cloud c1"></div><div class="cloud c2"></div><div class="hills hill-back"></div><div class="hills hill-front"></div><div class="scenery-tree t1">♣</div><div class="scenery-tree t2">♣</div><div class="ranch-sign">THE LITTLE RANCH<span>每一种关系，都有自己的节奏</span></div><div class="field-fence"></div><div class="ranch-residents">${data.people.length?data.people.slice(0,6).map(p=>`<button class="resident" data-action="person" data-id="${e(p.id)}">${creature(p)}<span>${e(p.name)}</span></button>`).join(''):`<button class="resident welcome-egg" data-action="new">${creature({})}<span>你的第一位牧场伙伴 ＋</span></button>`}</div><div class="field-flowers">✳ <span>✿</span> ✳</div><div class="landscape-note"><span class="live-dot"></span> ${data.people.length} 位伙伴 · ${hatched} 位已孵化</div></section><section class="section-heading"><div><div class="eyebrow">PEOPLE YOU CARE ABOUT</div><h2>我在意的人 <span class="count">${data.people.length}</span></h2></div><small>了解的成长，不代表关系的进度</small></section><div class="people-grid">${data.people.map(p=>`<button class="person-card" data-action="person" data-id="${e(p.id)}"><div class="card-art ${e(p.color||'sage')}">${creature(p)}</div><div class="card-copy"><div class="between"><h3>${e(p.name)}</h3><span class="arrow">↗</span></div><p>${p.goalType==='romance'?'♡ 发展亲密关系':'♧ 认识朋友'}</p><div class="between"><span class="pill">${p.stage==='hatched'?(p.profile?.stale?'画像待更新':'已孵化'):'等待孵化'}</span><small>${p.materials?.length||0} 份材料</small></div></div></button>`).join('')}<button class="add-card" data-action="new"><span>＋</span><h3>留一个位置</h3><p>只需要一个名字<br>其余的，慢慢了解</p></button></div><footer class="ranch-footer">先倾听，再靠近。<span>材料与画像保存在本机服务中</span></footer>`;}
function selfEvidence(data) {const self=data.self||{};return {...self,materials:[...new Map([...(self.materials||[]),...data.people.flatMap(p=>(p.materials||[]).filter(m=>m.speaker==='me'))].map(m=>[m.id,m])).values()]};}
function profileHistory(p,self){const items=(p.analyses||[]).filter(v=>JSON.stringify(v)!==JSON.stringify(p.profile));return items.length?`<details class="history"><summary>历史画像 · ${items.length} 份</summary>${[...items].reverse().map(v=>`<details><summary>${e(date(v.createdAt))} · 已保存画像</summary>${renderProfile(v,p,self)}</details>`).join('')}</details>`:'';}
function personPage(data,ui) {const p=data.people.find(p=>p.id===ui.selected);if(!p)return home(data);const running=jobActive(data.job);return `<button class="back text-button" data-action="ranch">← 回到牧场</button><header class="person-heading"><div class="portrait ${e(p.color||'sage')}">${creature(p)}</div><div class="person-title"><div class="eyebrow">${p.stage==='hatched'?'A LITTLE MORE UNDERSTANDING':'EVERY STORY STARTS SOMEWHERE'}</div><h1>${e(p.name)}</h1><p>${p.goalType==='romance'?'♡ 发展亲密关系':'♧ 认识朋友'}${p.goal?' · '+e(p.goal):''}</p><span class="pill">${p.stage==='hatched'?'已孵化 · 从真实材料中了解':'一颗等待了解的蛋'}</span></div>${button('edit','编辑人物','class="secondary"')}</header><nav class="tabs" aria-label="人物空间">${[['profile','人物画像'],['materials',`了解材料 · ${p.materials?.length||0}`],['strategy','相处攻略']].map(([v,t])=>button('tab',t,`data-tab="${v}" class="${ui.tab===v?'active':''}"`)).join('')}</nav><section class="detail-content">${ui.tab==='materials'?materials(p):ui.tab==='strategy'?`<div class="section-heading"><div><h2>下一步，如何自然靠近</h2><p>结合目标画像、双方材料、关系目标与启用资料。</p></div></div><div class="strategy-composer"><label for="situation">此刻的情境 <span>可选</span></label><textarea id="situation" rows="3" placeholder="想找个话题开启聊天，或粘贴对方刚发来的话…">${e(ui.draft||'')}</textarea><div class="between"><small>${!p.profile?'先生成对方画像，再制定攻略':p.profile.stale?'画像已过期，请先更新画像':'建议仅供参考；尊重对方的意愿与边界'}</small>${button('strategy','✧ 生成相处攻略',`class="primary" ${running||!p.profile||p.profile.stale?'disabled':''}`)}</div></div>${renderStrategy(p.strategies?.at(-1),p,selfEvidence(data))}${p.strategies?.length>1?`<details class="history"><summary>历史攻略 · ${p.strategies.length-1} 份</summary>${p.strategies.slice(0,-1).reverse().map(s=>`<details><summary>${e(date(s.createdAt))} · ${e(s.situation||s.overview).slice(0,100)}</summary>${renderStrategy(s,p,selfEvidence(data))}</details>`).join('')}</details>`:''}`:`<div class="section-heading"><div><h2>看见一个真实的人</h2><p>区分直接信息与推测，每个判断可回看原文。</p></div>${button('analyze',p.profile?'✧ 更新画像':'✧ 生成画像 · 孵化',`class="primary" ${running?'disabled':''}`)}</div>${renderProfile(p.profile,p,selfEvidence(data))}${profileHistory(p,selfEvidence(data))}${!p.profile?`<div class="empty-actions">${button('material-add','＋ 补充材料','class="secondary"')}${button('link-source','关联已有聊天','class="text-button"')}</div>`:''}`}</section>`;}
function selfPage(data,ui){const p={...data.self,id:'self'};return `<header class="page-heading"><div><div class="eyebrow">IT STARTS WITH YOU</div><h1>也多了解，<br>一点自己。</h1><p>表达你的期待与边界，让建议更贴近你。</p></div>${button('self-edit','编辑我的自述','class="secondary"')}</header><div class="self-description"><span class="self-mark">我</span><div><h2>${e(p.name||'我')}</h2><p>${e(p.about||'还没有自述，写下你想怎样与人相处。')}</p>${p.style?`<p><b>表达习惯</b> ${e(p.style)}</p>`:''}${p.boundaries?`<p><b>我的边界</b> ${e(p.boundaries)}</p>`:''}</div></div><nav class="tabs">${[['profile','我的画像'],['materials',`我的材料 · ${p.materials?.length||0}`]].map(([v,t])=>button('tab',t,`data-tab="${v}" class="${ui.tab===v?'active':''}"`)).join('')}</nav>${ui.tab==='materials'?materials(p):`<div class="section-heading"><div><h2>我的沟通与相处方式</h2><p>分析也会汇总其他人物材料中标为“我的发言”的内容；关联聊天时请选择自己的身份。</p></div>${button('analyze',p.profile?'✧ 更新我的画像':'✧ 生成我的画像',`class="primary" ${jobActive(data.job)?'disabled':''}`)}</div>${renderProfile(p.profile,p,selfEvidence(data))}${profileHistory(p,selfEvidence(data))}`}`;}
function library(data){return `<header class="page-heading"><div><div class="eyebrow">A SHELF FOR BETTER CONNECTIONS</div><h1>给相处，<br>多一些好思路。</h1><p>把值得参考的知识，放在随手可取的地方。</p></div>${button('upload','＋ 上传资料','class="primary"')}</header><div class="library-banner"><div class="book-stack"><i></i><i></i><i></i></div><div><h2>一本书，不是一个人的答案</h2><p>生成画像或攻略时，系统检索启用资料中的相关原文片段。<br>书中的观点会单独标注，始终与人物发言分开。</p></div></div><div class="section-heading"><h2>我的书架 <span class="count">${data.library.length}</span></h2><small>TXT · Markdown · PDF · DOCX · EPUB / 单份 ≤ 10 MB</small></div><div class="books-grid">${data.library.map((b,i)=>`<article class="book-card"><div class="book-cover tone-${i%3}"><span>REFERENCE LIBRARY</span><h3>${e(b.title)}</h3><small>${e((b.filename||'').split('.').at(-1)?.toUpperCase())}</small></div><div class="book-info"><h3>${e(b.title)}</h3><p>${e(b.characters||0)} 字 · ${e(b.chunkCount||0)} 个片段</p><div class="between">${button('knowledge-toggle',b.enabled?'● 已启用':'○ 已停用',`class="text-button ${b.enabled?'enabled':''}" data-id="${e(b.id)}"`)}${button('knowledge-delete','删除',`class="text-button danger" data-id="${e(b.id)}"`)}</div></div></article>`).join('')||'<div class="blank"><h3>书架还空着</h3><p>上传沟通、心理或关系相关的资料，<br>让下一次建议多一份可追溯的参考。</p></div>'}</div>`;}
export function renderRanch(data,ui={page:'ranch'}) {return `<div class="ranch"><aside class="sidebar"><a class="brand" href="/" aria-label="爱聊牧场首页"><span class="brand-mark">♧</span><span>爱聊牧场<small>THE LITTLE RANCH</small></span></a><div class="nav-label">我的小天地</div><nav aria-label="主导航">${[['ranch','⌂','牧场'],['self','◉','我的画像'],['library','▤','资料书架']].map(([a,i,t])=>button(a,`<span>${i}</span>${t}`,`class="nav-item ${ui.page===a||(a==='ranch'&&ui.page==='person')?'active':''}"`)).join('')}<a class="nav-item" href="/conversations.html"><span>▧</span>聊天材料 <small>↗</small></a></nav><div class="sidebar-bottom"><div class="sidebar-sprout">✳</div><p>不急着定义关系<br>先认真了解一个人</p><small><span class="live-dot"></span> 私人的了解空间</small></div></aside><main class="main">${renderJob(data,ui)}${ui.page==='person'?personPage(data,ui):ui.page==='self'?selfPage(data,ui):ui.page==='library'?library(data):home(data)}</main></div>`;}
